---

- name: "Clone or update {{ item.key }}"
  become: true
  become_user: "{{ user }}"
  ansible.builtin.git:
    repo: "{{ item.value }}"
    version: "{{ sucklessbranch }}"
    dest: "/home/{{ user }}/.local/src/{{ item.key }}"
    clone: true
    update: true
    force: true
  loop: "{{ gitrepos | dict2items }}"

- name: Build suckless
  ansible.builtin.shell: |
    set -e
    for dir in {{ gitrepos.keys() | map('quote') | join(' ') }}; do
      echo "Building $dir..."
      cd "/home/{{ user }}/.local/src/$dir"
      make install
    done
