---

- name: Ensure .tmp dir is empty
  become: true
  become_user: "{{ user }}"
  ansible.builtin.file:
    path: "/home/{{ user }}/.installtmp"
    state: absent

- name: Create a .tmp directory
  become: true
  become_user: "{{ user }}"
  ansible.builtin.file:
    path: "/home/{{ user }}/.installtmp"
    state: directory

- name: cloning dotfiles repo
  become: true
  become_user: "{{ user }}"
  ansible.builtin.git:
    repo: "{{ dotfilesrepo }}"
    dest: "/home/{{ user }}/.installtmp"
    clone: yes

- name: remove unneeded git files
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /home/{{ user }}/.installtmp/.git
    - /home/{{ user }}/.installtmp/README.md
    - /home/{{ user }}/.installtmp/LICENSE
    - /home/{{ user }}/.installtmp/FUNDING.yml

- name: copying dotfiles into config dir
  copy:
    src: "/home/{{ user }}/.installtmp/"
    remote_src: true
    dest: "/home/{{ user }}/"
    owner: "{{ user }}"
    group: wheel


- name: remove tmp dir
  file:
    path: "/home/{{ user }}/.installtmp"
    state: absent

- name: create zsh cache dir
  file:
    path: "/home/{{ user }}/.cache/zsh"
    owner: "{{ user }}"
    group: "wheel"
    state: directory

- name: create symlinks for zprofile
  file:
    src: "/home/{{ user }}/.config/shell/profile"
    dest: "/home/{{ user }}/.zprofile"
    owner: "{{ user }}"
    group: "wheel"
    state: link

- name: create symlinks for zshrc
  file:
    src: "/home/{{ user }}/.config/zsh/.zshrc"
    dest: "/home/{{ user }}/.zshrc"
    owner: "{{ user }}"
    group: "wheel"
    state: link


- name: create repo dir
  file:
    path: "/home/{{ user }}/repos"
    state: directory
    owner: "{{ user }}"
    group: wheel

- name: clone additional repos
  become: true
  become_user: "{{ user }}"
  ansible.builtin.git:
    repo: "{{ item.value }}"
    dest: "/home/{{ user }}/.local/src/{{ item.key }}"
    clone: true
  with_dict: "{{ additional_repos }}"
