---

- name: Ensure .tmp dir is empty
  become: yes
  become_user: anton
  ansible.builtin.file:
    path: "/home/{{ user }}/.installtmp"
    state: absent

- name: Create a .tmp directory
  become: yes
  become_user: anton
  ansible.builtin.file:
    path: "/home/{{ user }}/.installtmp"
    state: directory

- name: cloning dotfiles repo
  become: yes
  become_user: anton
  ansible.builtin.git:
    repo: "{{ dotfilesrepo }}"
    dest: "/home/{{ user }}/.installtmp"
    clone: yes

- name: remove unneeded git files
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /home/{{ user }}/.installtmp/.git
    - /home/{{ user }}/.installtmp/README.md
    - /home/{{ user }}/.installtmp/LICENSE
    - /home/{{ user }}/.installtmp/FUNDING.yml

- name: copying dotfiles into config dir
  copy:
    src: "/home/{{ user }}/.installtmp/"
    remote_src: yes
    dest: "/home/{{ user }}/"
    owner: "{{ user }}"
    group: wheel
    force: yes
    follow: yes

- name: remove tmp dir
  file:
    path: "/home/{{ user }}/.installtmp"
    state: absent

- name: create zsh cache dir
  file:
    path: "/home/{{ user }}/.cache/zsh"
    state: directory

- name: create repo dir
  file:
    path: "/home/{{ user }}/repos"
    state: directory
    owner: anton
    group: wheel

- name: clone additional repos
  become: yes
  become_user: anton
  ansible.builtin.git:
    repo: "{{ item.value }}"
    dest: "/home/{{ user }}/.local/src/{{ item.key }}"
    clone: yes
  with_dict: "{{ additional_repos }}"
