---
- name: Cloning dotfiles repo
  become: true
  become_user: "{{ user }}"
  ansible.builtin.git:
    repo: "{{ dotfilesrepo }}"
    version: "{{ dotfilesbranch }}"
    dest: "/home/{{ user }}/.local/share/larbs/"
    clone: true

- name: Create zsh cache dir
  ansible.builtin.file:
    path: "/home/{{ user }}/.cache/zsh"
    mode: '0700'
    owner: "{{ user }}"
    group: "wheel"
    state: directory
