---

- name: "clone {{ item.value }}"
  become: yes
  become_user: anton
  ansible.builtin.git:
    repo: "{{ item.value }}"
    dest: "/home/{{ user }}/.local/src/{{ item.key }}"
    clone: yes
  with_dict: "{{ gitrepos }}"

- name: "building {{ item.value }}"
  ansible.builtin.shell:
    cmd: make install
    chdir: "/home/{{ user }}/.local/src/{{ item.key }}"
  with_dict: "{{ gitrepos }}"


# - name: clone https://github.com/LukeSmithxyz/dwm
#   ansible.builtin.git:
#     repo: https://github.com/LukeSmithxyz/dwm
#     dest: /home/{{ user }}/.local/src/dwm
#     clone: yes

# - name: make https://github.com/LukeSmithxyz/dwm
#   ansible.builtin.shell:
#     cmd: make install
#     chdir: /home/{{ user }}/.local/src/dwm
