---

- name: Import Create_user.yml
  ansible.builtin.include_tasks: create_user.yml
- name: System upgrade
  community.general.pacman:
    update_cache: true
    upgrade: true


- name: Import dotfiles.yml
  ansible.builtin.include_tasks: dotfiles.yml
- name: Import pacman.yml
  ansible.builtin.include_tasks: pacman.yml
- name: Import aur.yml
  ansible.builtin.include_tasks: aur.yml

- name: Update system
  community.general.pacman:
    update_cache: true
    upgrade: true


- name: Get list of installed packages
  ansible.builtin.command: pacman -Qq
  register: installed_pkgs
  changed_when: false

- name: Get packages that are not yet installed
  ansible.builtin.set_fact:
    missing_packages: "{{ packages | difference(installed_pkgs.stdout_lines) }}"

- name: Install only missing packages
  community.general.pacman:
    name: "{{ missing_packages }}"
    state: present
  when: missing_packages | length > 0

- name: Install AUR packages
  kewlfft.aur.aur:
    name: "{{ item }}"
    state: present
  loop: "{{ aurpackages }}"
  become: true
  become_user: aur_builder
  ignore_errors: true

- name: Import gitmakeinstall.yml
  ansible.builtin.include_tasks: gitmakeinstall.yml

# - name: Link default wallpaper
#   ansible.builtin.file:
#     src: "/home/{{ user }}/.local/share/wallpapers/"
#     dest: "/home/{{ user }}/.local/share/bg"
#     owner: "{{ user }}"
#     group: wheel
#     state: link

- name: Check if swap file exists
  ansible.builtin.stat:
    path: "/swap/swapfile"
  register: swap_file_check

- name: Create swap file if it doesn't exist
  ansible.builtin.include_tasks: create_swapfile.yml
  when: not swap_file_check.stat.exists

- name: Display a message after playbook execution
  ansible.builtin.debug:
    msg: "Playbook has finished executing. Remember to check the system."
