- name: Ensure Python is installed
  raw: |
    if ! command -v python3 &> /dev/null; then
      pacman -Sy --noconfirm python
    fi
  become: true
  changed_when: false

- name: Create swap subvolume
  community.general.btrfs_subvolume:
    name: /@swap
    filesystem_label: SWAP
    snapshot_conflict: skip
  become: true

- name: Ensure swap file exists
  ansible.builtin.command: >
    btrfs filesystem mkswapfile --size 4g --uuid clear /swap/swapfile
  args:
    creates: /swap/swapfile
  register: swap_file_create
  become: true

- name: Set permissions on swap file
  ansible.builtin.file:
    path: /swap/swapfile
    owner: root
    group: root
    mode: '0600'

- name: Run swapon on the swap file
  ansible.builtin.command: swapon /swap/swapfile
  when: swap_file_create.changed
  register: swap_on
  failed_when: swap_on.rc != 0 and 'already in use' not in swap_on.stderr

- name: Add swapfile to fstab
  ansible.builtin.lineinfile:
    dest: /etc/fstab
    regexp: '^/swap/swapfile'
    line: '/swap/swapfile none swap defaults 0 0'
    state: present

- name: Set swappiness
  ansible.posix.sysctl:
    name: vm.swappiness
    value: 60
    state: present

- name: Check if 'resume' hook is already in /etc/mkinitcpio.conf
  ansible.builtin.shell: grep '^HOOKS=' /etc/mkinitcpio.conf | grep -o 'resume'
  register: grep_resume
  ignore_errors: true
  changed_when: false

- name: Insert 'resume' hook after 'filesystems' in /etc/mkinitcpio.conf
  ansible.builtin.replace:
    path: /etc/mkinitcpio.conf
    regexp: '^(HOOKS=.*filesystems)'
    replace: '\1 resume'
    backup: true
  when: grep_resume.stdout == ""
  notify: Rebuild_initramfs
