- name: Update keyring first
  community.general.pacman:
    name: archlinux-keyring
    state: latest
    update_cache: true
  become: true

- name: Update_system
  community.general.pacman:
    update_cache: true
    upgrade: true
  become: true

- name: Enable pacman colourised output and verbose package lists
  ansible.builtin.replace:
    path: /etc/pacman.conf
    regexp: '{{ item.regexp }}'
    replace: '{{ item.replace }}'
  with_items:
    - { regexp: '^#Color$', replace: 'Color' }
    - { regexp: '^#VerbosePkgLists$', replace: 'VerbosePkgLists' }
  become: true

- name: Enable repositories
  ansible.builtin.replace:
    path: /etc/pacman.conf
    regexp: '^#\[{{ item }}\]$\n^#Include\s+=\s+/etc/pacman.d/mirrorlist$'
    replace: '[{{ item }}]\nInclude = /etc/pacman.d/mirrorlist'
  with_items: '{{ pacman.repos }}'
  notify: Update pacman cache
  when: pacman.repos is defined
  become: true

- name: Ignore 'modified' group
  ansible.builtin.replace:
    path: /etc/pacman.conf
    regexp: '^#IgnoreGroup =$'
    replace: 'IgnoreGroup = modified'
  become: true

- name: Create the `aur_builder` user
  ansible.builtin.user:
    name: aur_builder
    shell: /bin/zsh
    group: wheel
    append: true
    create_home: true
  become: true

- name: Allow the `aur_builder` user to run `sudo pacman` without a password
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/11-install-aur_builder
    line: 'aur_builder ALL=(ALL) NOPASSWD: ALL'
    create: true
    mode: '0440'
    owner: root
    group: root
    validate: 'visudo -cf %s'
  become: true
