- name: Update_system
  community.general.pacman:
    update_cache: true
    upgrade: true

- name: Enable pacman colourised output and verbose package lists
  ansible.builtin.replace:
    path: /etc/pacman.conf
    regexp: '{{ item.regexp }}'
    replace: '{{ item.replace }}'
  with_items:
    - { regexp: '^#Color$', replace: 'Color' }
    - { regexp: '^#VerbosePkgLists$', replace: 'VerbosePkgLists' }

- name: Enable repositories
  ansible.builtin.replace:
    path: /etc/pacman.conf
    regexp: '^#\[{{ item }}\]$\n^#Include\s+=\s+/etc/pacman.d/mirrorlist$'
    replace: '[{{ item }}]\nInclude = /etc/pacman.d/mirrorlist'
  with_items: '{{ pacman.repos }}'
  notify: Update pacman cache
  when: pacman.repos is defined

- name: Ignore 'modified' group
  ansible.builtin.replace:
    path: /etc/pacman.conf
    regexp: '^#IgnoreGroup =$'
    replace: 'IgnoreGroup = modified'

- name: Create the `aur_builder` user
  become: true
  ansible.builtin.user:
    name: aur_builder
    create_home: true
    group: wheel

- name: Allow the `aur_builder` user to run `sudo pacman` without a password
  become: true
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/11-install-aur_builder
    line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
    create: true
    mode: '0440'
    owner: root
    group: root
    validate: 'visudo -cf %s'
