- name: Get list of installed packages
  ansible.builtin.command: pacman -Qq
  register: installed_pkgs
  changed_when: false

- name: Determine missing packages
  ansible.builtin.set_fact:
    missing_packages: "{{ packages | difference(installed_pkgs.stdout_lines) }}"

- name: Show missing packages
  ansible.builtin.debug:
    msg: "Installing: {{ missing_packages }}"
  when: missing_packages | length > 0

- name: Install only missing packages
  community.general.pacman:
    name: "{{ missing_packages }}"
    state: present
  when: missing_packages | length > 0

- name: Ensure .ansible/tmp exists and is owned by aur_builder
  ansible.builtin.file:
    path: /home/aur_builder/.ansible/tmp
    state: directory
    owner: aur_builder
    group: wheel
    mode: '0700'

- name: Install yay
  kewlfft.aur.aur:
    name: "yay"
    use: makepkg
    state: present
  become: true
  become_user: aur_builder
  ignore_errors: true

- name: Install aur packages
  community.general.pacman:
    name: "{{ aur_packages }}"
    executable: yay
    state: present
  become: true
  become_user: aur_builder
  ignore_errors: true

# - name: Install AUR packages
#   kewlfft.aur.aur:
#     name: "{{ aurpackages }}"
#     use: yay
#     state: present
#   become: true
#   become_user: aur_builder
#   ignore_errors: true
